name: Update Cloudflare Blocklist

on:
  schedule:
    - cron: '15 0 * * *' # tiap hari jam 00:00 UTC
  workflow_dispatch:     # bisa trigger manual

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install npm dependencies
        run: npm ci

      # 4️⃣ Verify files (optional)
      - name: Verify scripts exist
        run: ls -l

      # 5️⃣ Download and prepare blocklist
      - name: Download AdGuard blocklist
        env:
          BLOCKLIST_URL: 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt'
        run: node download_lists.js

      # 6️⃣ Create / update Cloudflare Domain List
      - name: Update Domain List
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          LIST_NAME: 'AdGuard_Ads_Block'
        run: node cf_list_create.js

      # 7️⃣ Create / update DNS policy
      - name: Create DNS Policy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          POLICY_NAME: 'Block_AdGuard_Ads_Block'
          LIST_NAME: 'AdGuard_Ads_Block'
        run: node cf_gateway_rule_create.js
