name: Update Cloudflare Blocklist

on:
  schedule:
    - cron: '15 0 * * *'  # tiap hari jam 00:00 UTC
  workflow_dispatch:      # bisa trigger manual

jobs:
  update-blocklist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requests
        run: pip install requests

      - name: Run update script
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          LIST_NAME: 'AdGuardList'
          BLOCKLIST_URL: 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt'
        run: ./python update_cf_list.py
